import React from "react";
import { Container } from "@material-ui/core";
import FilterableJobAdTable from "../components/filter/FilterableJobAdTable";

export default function FilterableJobAdTablePage() {
  return (
    <Container style={{ width: "1000px" }}>
      <div>
        <FilterableJobAdTable jobads={JOBADS} />
      </div>
    </Container>
  );
}

const JOBADS = [
  {
    id: 0,
    location: {
      Sejong: false,
      Busan: false,
      Chungcheongbuk: false,
      Chungcheongnam: false,
      Daegu: false,
      Daejeon: false,
      Gangwon: false,
      Gwangju: false,
      Gyeonggi: true,
      Gyeongsangbuk: false,
      Gyeongsangnam: false,
      Incheon: false,
      Jeju: false,
      Jeollabuk: false,
      Jeollanam: false,
      Seoul: false,
      Ulsan: false,
    },
    // location: {
    //   세종: false,
    //   부산: false,
    //   충북: false,
    //   충남: false,
    //   대구: false,
    //   대전: false,
    //   강원: false,
    //   광주: false,
    //   경기: true,
    //   경북: false,
    //   경남: false,
    //   인천: false,
    //   제주: false,
    //   전북: false,
    //   전남: false,
    //   서울: false,
    //   울산: false,
    // },
    title: "졸전 모형 어시 급구",
    reward: {
      money: true,
      talentExc: true,
    },
    // reward: {
    //   돈: true,
    //   어시교환: true,
    // },
    todo: {
      panel: true,
      diagram: true,
      drawing: true,
      errand: true,
      etc: true,
      model: true,
    },
    // todo: {
    //   판넬작업: true,
    //   다이어그램: true,
    //   도면작업: true,
    //   심부름: true,
    //   기타업무: true,
    //   모형작업: true,
    // },
    gender: {
      f: true,
      m: true,
      n: false,
    },
    // gender: {
    //   여성: true,
    //   남성: true,
    //   무관: false,
    // },
  },
  {
    id: 1,
    location: {
      Sejong: true,
      Busan: false,
      Chungcheongbuk: false,
      Chungcheongnam: false,
      Daegu: false,
      Daejeon: false,
      Gangwon: false,
      Gwangju: false,
      Gyeonggi: false,
      Gyeongsangbuk: false,
      Gyeongsangnam: false,
      Incheon: false,
      Jeju: false,
      Jeollabuk: false,
      Jeollanam: false,
      Seoul: false,
      Ulsan: false,
    },
    title: "판넬 어시 급구",
    reward: {
      money: true,
      talentExc: false,
    },
    todo: {
      panel: true,
      diagram: true,
      drawing: false,
      errand: false,
      etc: false,
      model: false,
    },
    gender: {
      f: true,
      m: false,
      n: false,
    },
  },
  {
    id: 2,
    location: {
      Sejong: false,
      Busan: true,
      Chungcheongbuk: false,
      Chungcheongnam: false,
      Daegu: false,
      Daejeon: false,
      Gangwon: false,
      Gwangju: false,
      Gyeonggi: false,
      Gyeongsangbuk: false,
      Gyeongsangnam: false,
      Incheon: false,
      Jeju: false,
      Jeollabuk: false,
      Jeollanam: false,
      Seoul: false,
      Ulsan: false,
    },
    title: "심부름 어시 급구",
    reward: {
      money: true,
      talentExc: false,
    },
    todo: {
      panel: false,
      diagram: false,
      drawing: false,
      errand: true,
      etc: true,
      model: false,
    },
    gender: {
      f: false,
      m: false,
      n: true,
    },
  },
  {
    id: 3,
    location: {
      Sejong: false,
      Busan: false,
      Chungcheongbuk: false,
      Chungcheongnam: false,
      Daegu: false,
      Daejeon: false,
      Gangwon: false,
      Gwangju: false,
      Gyeonggi: false,
      Gyeongsangbuk: false,
      Gyeongsangnam: false,
      Incheon: false,
      Jeju: true,
      Jeollabuk: false,
      Jeollanam: false,
      Seoul: false,
      Ulsan: false,
    },
    title: "도면 어시 급구",
    reward: {
      money: false,
      talentExc: true,
    },
    todo: {
      panel: false,
      diagram: false,
      drawing: true,
      errand: false,
      etc: false,
      model: false,
    },
    gender: {
      f: false,
      m: true,
      n: false,
    },
  },
];
